# Site settings
title: JYT's Blog
email: jiangla7201@163.com
url: https://jiangla72.github.io/YutingJiang.github.io/
description: "这里是一头小白菜，正在努力学习中

c,c++，Linux,python,机器学习ml，Javascript，HTML，CSS..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: JYT’s Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/Jiangla72

# Build settings
markdown: kramdown
permalink: pretty